---
title: "Zeyd Khalil HW7, October 8, 2020"
output: pdf_document
---

```{r}
suppressPackageStartupMessages(library(tidyverse))
suppressPackageStartupMessages(library(tidyverse))
dfdat <- tribble(
  ~date,        ~time,      ~number, ~factor, ~logical,
  ##----------  ----------  -------  -------  --------
  "12-01-1988", "10:10:02", "2",     "A",     "TRUE",
  "11-12-1987", "11:10:57", "4",     "A",     "TRUE",
  "02-03-1989", "10:10:25", "6",     "B",     "FALSE",
  "06-03-1982", "22:10:55", "2",     "B",     "TRUE",
  "09-21-1981", "10:10:02", "1",     "A",     "FALSE"
  )
dfdat
```  

# Exercise 1  

```{r}
parse_date("01, January 2018", format = "%d, %B %Y")
parse_date("01-January/2000", format = "%d-%B/%Y")
parse_date("1 Jan 19", format = "%d %b %y")
```  

# Exercise 2  

```{r}
parse_time("10:40 pm", format = "%I:%M %p")
parse_time("23:40-22", format = "%H:%M-%S")
```

# Exercise 3   

```{r, warning=FALSE}
covidstats <- read_csv("owid-covid-data.csv", col_types = cols(date = col_date()))

covidstats$new_tests <- covidstats$total_tests <- covidstats$total_tests_per_thousand <- covidstats$new_tests_per_thousand <- covidstats$new_tests_smoothed <- covidstats$new_tests_smoothed_per_thousand <- covidstats$tests_per_case <- covidstats$positive_rate <- covidstats$tests_units <- NULL

head(covidstats)

summary(covidstats)

write_csv(covidstats, "Data/owid-covid-data.csv", append = TRUE, na = "NA")
```  

> In order to clean my dataset, I removed all of the useless columns that had no values in them. 